Coworking
WildCodeSchool-2023-09/php-p2-strasgite pull request #14
Opened 2023-11-16 15:02 UTC by kykileur

2023-11-16 15:06 UTC, kykileur reviewed
je pense que c'est good

2023-11-16 15:13 UTC, Yazzz28 approved these changes

2023-11-16 15:19 UTC, StyMey requested changes

2023-11-16 15:19 UTC, StyMey commented on src/View/include/_navbar.html.twig
> +							<a href="/logout">Deconnection</a>
Ca s'écrit: Déconnexion

2023-11-16 15:35 UTC, kykileur commented on src/View/include/_navbar.html.twig
> +							<a href="/logout">Deconnection</a>
normalement c good

2023-11-16 20:49 UTC, vincentr-wcs requested changes

2023-11-16 20:49 UTC, vincentr-wcs commented on src/Model/AbstractManager.php
> +    public const TABLE = 'contact';
Ici faut laisser TABLE vide et redéfinir la public const table dans le ContactManager

2023-11-16 20:49 UTC, vincentr-wcs commented on src/View/contact/_contact.html.twig
> +                    {% if errors.firstname is defined %}
if c'est plutôt ça : 
```suggestion
                    {% if errors.phone is defined %} 
```

2023-11-16 20:49 UTC, vincentr-wcs commented on src/View/contact/_contact.html.twig
> +                    {% if errors.firstname is defined %}
Ici c'est plutôt 
```suggestion
                    {% if errors.email is defined %} 
```

2023-11-18 22:19 UTC, yavuzkutuk commented
@kykileur Conflict à régler

2023-11-20 08:43 UTC, kykileur reviewed
je crois avoir tout bien remis

2023-11-20 08:43 UTC, kykileur commented on src/Model/AbstractManager.php
> +    public const TABLE = 'contact';
c'est fais

2023-11-20 09:59 UTC, antoninbrdl24 approved these changes

2023-11-20 14:44 UTC, StyMey requested changes

2023-11-20 14:44 UTC, StyMey commented on src/View/include/_navbar.html.twig
> +							<a href="/logout">Deconnection</a>
Tu n'as pas changé l'orthographe, je crois

2023-11-20 15:31 UTC, StyMey approved these changes

2023-11-20 15:53 UTC, vincentr-wcs approved these changes

2023-11-20 15:53 UTC, merged