Reservation
WildCodeSchool-2023-09/php-p2-strasgite pull request #15
Opened 2023-11-16 15:28 UTC by antoninbrdl24

2023-11-16 15:33 UTC, kykileur approved these changes

2023-11-16 20:42 UTC, vincentr-wcs requested changes

2023-11-16 20:42 UTC, vincentr-wcs commented on src/Controller/ReservationController.php
> +            }*/
Si ce code ne te sert plus tu pourrais l'enlever haha

2023-11-16 20:42 UTC, vincentr-wcs commented on src/Model/DashboardManager.php
> +    }
Pas compris  à quoi te sert ses deux méthodes ? Elle devrait pas aller plutôt dans le DashboardController ?

2023-11-16 20:42 UTC, vincentr-wcs commented on src/View/Admin/Dashboard/index.html.twig
> +					{{dump(reservation)}}
On laisse pas traîner de dump dans le code

2023-11-16 20:42 UTC, vincentr-wcs commented on src/View/Admin/Dashboard/index.html.twig
> +						{{dump(reservation)}}
idem ici

2023-11-17 21:33 UTC, vincentr-wcs approved these changes
Bien joué !

2023-11-17 21:34 UTC, merged