add fist room
WildCodeSchool-2023-09/php-p2-strasgite pull request #7
Opened 2023-11-07 11:00 UTC by StyMey

2023-11-07 11:13 UTC, kykileur approved these changes

2023-11-07 11:19 UTC, Yazzz28 approved these changes

2023-11-07 12:50 UTC, vincentr-wcs commented
Attention ici y'a tous les checks ne sont pas passés, faut les corriger pour qu'on valide la PR

2023-11-08 09:40 UTC, yavuzkutuk commented
@StyMey il y a comme un problème

2023-11-09 09:16 UTC, vincentr-wcs requested changes
Juste unn petit changement à faire et ça sera good :D

2023-11-09 09:16 UTC, vincentr-wcs commented on public/assets/css/style.css
> +@import url('_main-room.css');
Il faut mettre les fichiers de style après celui Uikit car vous surchargez Uikit avec votre css.

2023-11-10 12:35 UTC, vincentr-wcs approved these changes

2023-11-10 12:36 UTC, merged