Login
WildCodeSchool-2023-09/php-p2-strasgite pull request #9
Opened 2023-11-09 12:58 UTC by Yazzz28

2023-11-09 14:03 UTC, vincentr-wcs commented
@Yazzz28 Tu as des conflits à régler.

2023-11-09 15:57 UTC, StyMey approved these changes

2023-11-09 16:03 UTC, antoninbrdl24 approved these changes
choqué du niveau

2023-11-09 16:13 UTC, kykileur approved these changes

2023-11-09 21:19 UTC, vincentr-wcs requested changes
Sacré PR haha. Quelques petits changements et ça devrait le faire bien joué !

2023-11-09 21:19 UTC, vincentr-wcs commented on src/Controller/AbstractController.php
> +        //$this->user = isset($_SESSION['isLogin'])?$userManager->userLogin($_SESSION['isLogin']):false;
Si tu ne l'utilise pas peut-être retire le dans une prochaine PR ;)

2023-11-09 21:19 UTC, vincentr-wcs commented on src/Controller/DashboardController.php
> +        }*/
Tu as oublié d'enlever la version qui ne fonctionnait pas.

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/Admin/Dashboard/index.html.twig
> +                            <a href="admin/message/{{ message.id }}/delete" class="uk-button uk-button-danger">Supprimer</a>
Cette route ne fonctionnera pas car pour supprimer le bon message il te faut dans ton url une query string où tu passes ton id du genre ?id=message.id

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/Admin/Dashboard/index.html.twig
> +                            <a href="admin/message/{{ message.id }}" class="uk-button uk-button-primary">Voir</a>
Cette route ne fonctionnera pas car pour voir le bon message il te faut dans ton url une query string ou tu passes ton id du genre ?id=message.id

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/Admin/Dashboard/index.html.twig
> +                            <a href="admin/reservation/{{ reservation.id }}" class="uk-button uk-button-primary">Voir</a>
Idem que plus haut

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/Admin/Dashboard/index.html.twig
> +                            <a href="admin/reservation/{{ reservation.id }}/delete" class="uk-button uk-button-danger">Supprimer</a>
idem que plus haut

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/Security/_login.html.twig
> +endblock %} {% block content %}
attention à l'indentation des fichiers

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/Security/_login.html.twig
> +    <form action="#" method="POST">
Pas besoin de mettre action ici ou alors si tu le mets, mets la même route que dans ton back soit ta page d'accueil donc  '/'

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/Security/_signin.html.twig
> +	<form action="#" method="post">
idem que plus haut

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/include/_navbar.html.twig
> +					{{ dump(session) }}
On ne laisse pas traîner de dump dans les fichier haha

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/include/_navbar.html.twig
> +	<div class="uk-container">
En réglant tes conflit j'ai l'impression que tu as décalé tout l'indentation des fichiers

2023-11-09 21:19 UTC, vincentr-wcs commented on src/View/layout.html.twig
> +		{% include "/include/_footer.html.twig" %}
On met le JS à la fin là il faudrait remonter ton footer au dessus du block js

2023-11-10 08:48 UTC, vincentr-wcs approved these changes
Bien joué super boulot !

2023-11-10 08:48 UTC, merged